### ISSUE TITLE
Feature selection

### ISSUE THREAD

**Issue by RichardScottOZ** [fnaghetini/Mapa-Preditivo#25]
Any particular reason for using the cirrus and panchromatic bands?

No magnetics available?

**Comment by fnaghetini** [comment]
@RichardScottOZ good point. It doesn't make any sense using these bands. We'll remove these layers soon. Thanks for point that out!

We do have magnetics available, but we're just using analytic signal

**Comment by RichardScottOZ** [comment]
If your modelling suggests they add value, it would be surprising, anyway!

Analytic signal makes sense, sure.

**Comment by fnaghetini** [comment]
We've just removed both cirrus and pan bands, as well as renamed notebooks to more meaningful names, as you suggested. Check PR #28 if you'd like to 😃.
