### ISSUE TITLE
Geospatial output

### ISSUE THREAD

**Issue by RichardScottOZ** [fnaghetini/Mapa-Preditivo#26]
The first thing an exploration geologist will ask for after seeing this...is a map. Should be straightforward to make a raster output function and polygonise those, given what you have already.

**Comment by RichardScottOZ** [comment]
This framework takes a bunch of rasters [geotiffs] and training locations and handles some of the work for you - and outputs geotiffs similarly.

**Comment by fnaghetini** [comment]
Fully agree! Thanks for sharing this framework and for your time, we'll check it out for sure. Actually, this is our (Franco & Guilherme) first work on predictive lithological mapping. Thus, feel free to give opinions and feedbacks! It is pretty important for us!

**Comment by guiasilveira** [comment]
We appreciate your feedbacks, Richard. This project is part of our undergraduate final project, so every advice and questions are extremely helpful

**Comment by fnaghetini** [comment]
@RichardScottOZ , we've just added a new helper function [df2Raster](https://github.com/fnaghetini/Mapa-Preditivo/blob/main/functions/Custom_Export.py) that converts a dataframe to a raster TIF file and saves it. These output rasters can be found [here](https://github.com/fnaghetini/Mapa-Preditivo/tree/main/output). Check PR #29 if you'd like to.

Thanks again for the tip!

-Franco

**Comment by RichardScottOZ** [comment]
Yes, just had a look at one.  Good work.
